// DMX.
// Copyright (C) Eugene Bekker.

using static System.Runtime.InteropServices.JavaScript.JSType;

namespace DMX.WebUI3.Events;

/// <summary>
/// Represents the method that will handle an event that has no event data.
/// </summary>
/// <param name="sender">The source of the event.</param>
/// <param name="ev">An object that contains no event data.</param>
public delegate void AsyncEventHandler(object? sender, AsyncEventArgs ev);

/// <summary>
/// Represents the method that will handle an event when the event provides data.
/// </summary>
/// <typeparam name="TEventArgs">
/// The type of the event data generated by the event.
/// </typeparam>
/// <param name="sender">The source of the event.</param>
/// <param name="ev">An object that contains the event data.</param>
public delegate void AsyncEventHandler<TAsyncEventArgs>(object? sender, TAsyncEventArgs ev)
    where TAsyncEventArgs : AsyncEventArgs;
